#!/bin/bash

set -e

# config file generated by home assistant
JSON_FILE="/data/options.json"

# read options json and export values
if [ -f "$JSON_FILE" ]; then
    eval "$(cat $JSON_FILE | jq -r 'to_entries[] | "export \(.key)=\(.value)"')"
fi

exec python -m grobro.ha_bridge
